on:
  push:
    branches:
      - main
      - master
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v5
      - name: run tests
        run: npm test